name       : python-spyder-kernels
version    : 0.4.4
release    : 2
source     :
    - https://github.com/spyder-ide/spyder-kernels/archive/v0.4.4.tar.gz : 5ec65634e5b999b71a8542df30fa6e609b21637c1e6cc0867954105a8e667e98
license    :
    - MIT
component  : programming.ide
summary    : Jupyter Kernels for the Spyder console
description: |
    Package that provides Jupyter kernels for use with the consoles of Spyder, the Scientific Python Development Environment.
    These kernels can launched either through Spyder itself or in an independent Python session, and allow for interactive or file-based execution of Python code inside Spyder.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-cloudpickle
    - python-ipykernel
    - python-wurlitzer
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
