name       : python-spyder-kernels
version    : 2.4.1
release    : 23
source     :
    - https://github.com/spyder-ide/spyder-kernels/archive/refs/tags/v2.4.1.tar.gz : fa1ce0c2c78a736c54d85d4284c245dbd865f844c0f927c373a107f155f3f380
homepage   : https://github.com/spyder-ide/spyder-kernels
license    : MIT
component  : programming.ide
summary    : Jupyter Kernels for the Spyder console
description: |
    Package that provides Jupyter kernels for use with the consoles of Spyder, the Scientific Python Development Environment. These kernels can launched either through Spyder itself or in an independent Python session, and allow for interactive or file-based execution of Python code inside Spyder.
rundeps    :
    - python-cloudpickle
    - python-ipykernel
    - python-wurlitzer
build      : |
    %python3_setup
install    : |
    %python3_install
