name       : python-spyder-kernels
version    : 0.2.4
release    : 1
source     :
    - https://github.com/spyder-ide/spyder-kernels/archive/v0.2.4.tar.gz : 1fa27ba18f8673eb2b64082c6c8958d3e441a0721203615d354aa8dd10e8e4b1
license    :
    - MIT
component  : programming.ide
summary    : Jupyter Kernels for the Spyder console
description: |
    Jupyter Kernels for the Spyder console.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-cloudpickle
    - python-ipykernel
    - python-jupyter_client
    - python-pyzmq
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
