name       : python-spyder-kernels
version    : 2.3.3
release    : 21
source     :
    - https://github.com/spyder-ide/spyder-kernels/archive/refs/tags/v2.3.3.tar.gz : eede29c2100b31edea84a650ac49d8748d0c8319ff573a0f69f2d8c566adee66
homepage   : https://github.com/spyder-ide/spyder-kernels
license    : MIT
component  : programming.ide
summary    : Jupyter Kernels for the Spyder console
description: |
    Package that provides Jupyter kernels for use with the consoles of Spyder, the Scientific Python Development Environment. These kernels can launched either through Spyder itself or in an independent Python session, and allow for interactive or file-based execution of Python code inside Spyder.
rundeps    :
    - python-cloudpickle
    - python-ipykernel
    - python-wurlitzer
build      : |
    %python3_setup
install    : |
    %python3_install
