name       : python-spyder-kernels
version    : 2.2.1
release    : 16
source     :
    - https://github.com/spyder-ide/spyder-kernels/archive/refs/tags/v2.2.1.tar.gz : f9bca9db3c7955b6ed0c1fa70d188d7eb904b88a1cccb704a8465f619259b989
homepage   : https://github.com/spyder-ide/spyder-kernels
license    : MIT
component  : programming.ide
summary    : Jupyter Kernels for the Spyder console
description: |
    Package that provides Jupyter kernels for use with the consoles of Spyder, the Scientific Python Development Environment. These kernels can launched either through Spyder itself or in an independent Python session, and allow for interactive or file-based execution of Python code inside Spyder.
rundeps    :
    - python-cloudpickle
    - python-ipykernel
    - python-wurlitzer
build      : |
    %python3_setup
install    : |
    %python3_install
