name       : python-spyder-kernels
version    : 0.5.1
release    : 3
source     :
    - https://github.com/spyder-ide/spyder-kernels/archive/v0.5.1.tar.gz : 9f891d9a856bcee6be5d2f8ad5718951408a37792cdd0872ef4de54a8e09110c
license    :
    - MIT
component  : programming.ide
summary    : Jupyter Kernels for the Spyder console
description: |
    Package that provides Jupyter kernels for use with the consoles of Spyder, the Scientific Python Development Environment.
    These kernels can launched either through Spyder itself or in an independent Python session, and allow for interactive or file-based execution of Python code inside Spyder.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-cloudpickle
    - python-ipykernel
    - python-wurlitzer
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
